sudo: required
services:
  - docker

before_install:
  - docker build -t markweldonbrewer/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true markweldonbrewer/docker-react npm run test -- --coverage
