sudo: required
services:
  - docker

before_install:
  - docker build -t markweldonbrewer/docker-react -f Dockerfile.dev .

script:
  - docker run markweldonbrewer/docker-react npm run test -- --coverage
